# Generated by Django 5.0.14 on 2026-02-12 23:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
                ('emissive', models.CharField(max_length=20)),
                ('position', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=3)),
                ('size', models.FloatField()),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('planet_type', models.CharField(choices=[('lightning', 'Lightning'), ('snow', 'Snow'), ('deformed', 'Deformed'), ('tentacles', 'Tentacles'), ('craters', 'Craters'), ('terra', 'Terra')], max_length=20)),
                ('planet_name', models.CharField(max_length=200)),
                ('icon_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Army',
                'verbose_name_plural': 'Armies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BattleReport',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('factions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('mission', models.CharField(max_length=200)),
                ('points', models.IntegerField()),
                ('date', models.DateField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('player1_name', models.CharField(max_length=200)),
                ('player1_faction', models.CharField(max_length=100)),
                ('player1_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None)),
                ('player2_name', models.CharField(max_length=200)),
                ('player2_faction', models.CharField(max_length=100)),
                ('player2_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None)),
                ('key_moments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('mvp', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ArmyImage',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('army', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.army')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('phase', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative', to='api.battlereport')),
            ],
            options={
                'ordering': ['order', 'turn'],
            },
        ),
        migrations.CreateModel(
            name='PaintingGuide',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('difficulty', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('estimated_time', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=200)),
                ('date_created', models.DateField()),
                ('cover_image', models.URLField(max_length=500)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='api.army')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='GuideMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='api.paintingguide')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('guide', 'Painting Guide'), ('report', 'Battle Report')], max_length=20)),
                ('author', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battle_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.battlereport')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.paintingguide')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('content_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_id', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=20)),
                ('content_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_id', 'content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), default=list, size=None)),
                ('tips', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.paintingguide')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('guide', 'step_number')},
            },
        ),
    ]
