# Generated by Django 5.0.14 on 2026-02-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='color',
        ),
        migrations.RemoveField(
            model_name='army',
            name='emissive',
        ),
        migrations.RemoveField(
            model_name='army',
            name='planet_name',
        ),
        migrations.RemoveField(
            model_name='army',
            name='planet_type',
        ),
        migrations.RemoveField(
            model_name='army',
            name='position',
        ),
        migrations.RemoveField(
            model_name='army',
            name='size',
        ),
    ]
