# Generated by Django 5.0.14 on 2026-02-13 00:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_army_color_remove_army_emissive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='army',
            name='emissive',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='army',
            name='planet_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='army',
            name='planet_type',
            field=models.CharField(choices=[('lightning', 'Lightning'), ('snow', 'Snow'), ('deformed', 'Deformed'), ('tentacles', 'Tentacles'), ('craters', 'Craters'), ('terra', 'Terra')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='army',
            name='position',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0, 0, 0], size=3),
        ),
        migrations.AddField(
            model_name='army',
            name='size',
            field=models.FloatField(default=1.0),
        ),
    ]
