# Generated by Django 5.0.14 on 2026-02-13 00:32

import api.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_army_color_army_emissive_army_planet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='position',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=api.models.default_position, size=3),
        ),
    ]
