# Generated by Django 5.0.14 on 2026-02-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_army_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='planet_type',
            field=models.CharField(choices=[('lightning', 'Lightning'), ('snow', 'Snow'), ('deformed', 'Deformed'), ('tentacles', 'Tentacles'), ('craters', 'Craters'), ('terra', 'Terra'), ('standard', 'Standard')], default='standard', max_length=20),
        ),
    ]
