# Generated by Django 5.0.14 on 2026-02-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_army_planet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='armyimage',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battlereport',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
