# Generated by Django 5.0.14 on 2026-03-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_army_translations'),
        ('api', '0007_loreentry'),
    ]

    operations = [
    ]
