# Generated by Django 5.0.14 on 2026-03-16 15:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_0007_army_translations_0007_loreentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlereport',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), default=list, size=None),
        ),
    ]
