# Generated by Django 5.0.14 on 2026-03-16 15:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_battle_images_and_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('content', models.TextField(help_text='Contenido en formato Markdown')),
                ('excerpt', models.CharField(blank=True, max_length=500)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), default=list, size=None)),
                ('author', models.CharField(default='Administratum', max_length=200)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artículo de Noticias',
                'verbose_name_plural': 'Artículos de Noticias',
                'ordering': ['-published_at'],
            },
        ),
    ]
