# Generated by Django 5.0.14 on 2026-03-26 08:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_paint_guidematerial_paint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('sin_montar', 'Sin montar / En caja'), ('montada', 'Montada'), ('imprimada', 'Imprimada'), ('pintada_parcial', 'Pintada parcialmente'), ('pintada', 'Pintada completamente'), ('conversion', 'Conversión / Custom')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('faction', models.CharField(blank=True, max_length=200)),
                ('game', models.CharField(blank=True, max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('sold', 'Vendido')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='guidematerial',
            name='name',
            field=models.CharField(help_text='Nombre del material (auto-rellenado al elegir pintura)', max_length=300),
        ),
        migrations.AlterField(
            model_name='paint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.listing')),
            ],
            options={
                'verbose_name': 'Solicitud de compra',
                'verbose_name_plural': 'Solicitudes de compra',
                'ordering': ['-created_at'],
            },
        ),
    ]
