# Generated by Django 5.0.14 on 2026-03-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='sale_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('confirmed', 'Confirmado'), ('closed', 'Cerrado / Vendido'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
