# Generated by Django 5.0.14 on 2026-04-01 09:59
# Fixed: use IF NOT EXISTS for paintingguide columns that may already exist in production

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_purchase_request_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Use raw SQL with IF NOT EXISTS to avoid errors if columns already exist in production
        migrations.RunSQL(
            sql="ALTER TABLE api_paintingguide ADD COLUMN IF NOT EXISTS is_premium boolean NOT NULL DEFAULT false;",
            reverse_sql="SELECT 1;",  # non-destructive reverse
            state_operations=[
                migrations.AddField(
                    model_name='paintingguide',
                    name='is_premium',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="ALTER TABLE api_paintingguide ADD COLUMN IF NOT EXISTS price integer NULL;",
            reverse_sql="SELECT 1;",
            state_operations=[
                migrations.AddField(
                    model_name='paintingguide',
                    name='price',
                    field=models.IntegerField(blank=True, help_text='Precio en céntimos (499 = 4,99€)', null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField(blank=True)),
                ('favorite_faction', models.CharField(blank=True, max_length=100)),
                ('player_types', models.CharField(blank=True, max_length=200)),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='GuidePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=500, unique=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=500)),
                ('amount_paid', models.IntegerField(help_text='Precio pagado en céntimos')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.paintingguide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra de guía',
                'verbose_name_plural': 'Compras de guías',
                'unique_together': {('user', 'guide')},
            },
        ),
    ]
