# Generated by Django 5.0.14 on 2026-04-01 10:18
# Uses IF NOT EXISTS to be safe in case columns were already added manually.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_userprofile_add_missing_columns'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE api_battlereport ADD COLUMN IF NOT EXISTS youtube_url varchar(500) NOT NULL DEFAULT '';",
            reverse_sql="SELECT 1;",
            state_operations=[
                migrations.AddField(
                    model_name='battlereport',
                    name='youtube_url',
                    field=models.URLField(blank=True, help_text='URL del vídeo de YouTube (opcional)', max_length=500),
                ),
            ],
        ),
        migrations.RunSQL(
            sql="ALTER TABLE api_paintingguide ADD COLUMN IF NOT EXISTS youtube_url varchar(500) NOT NULL DEFAULT '';",
            reverse_sql="SELECT 1;",
            state_operations=[
                migrations.AddField(
                    model_name='paintingguide',
                    name='youtube_url',
                    field=models.URLField(blank=True, help_text='URL del vídeo de YouTube (opcional)', max_length=500),
                ),
            ],
        ),
    ]
