# Generated by Django 5.0.14 on 2026-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userprofile_favorite_armies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loreentry',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
