# Generated by Django 5.0.14 on 2026-04-05 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_loreentry_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_avatar',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='lore_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.loreentry'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.newsarticle'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.CharField(choices=[('guide', 'Painting Guide'), ('report', 'Battle Report'), ('news', 'News Article'), ('lore', 'Lore Entry')], max_length=20),
        ),
    ]
