"""
Management command to populate the Army Builder with Warhammer 40k 10th edition data.
Points values are based on Munitorum Field Manual 2024.
"""
from django.core.management.base import BaseCommand
from api.models import BuilderFaction, BuilderDatasheet


FACTIONS_DATA = [
    {
        'id': 'space-marines',
        'name': 'Space Marines',
        'short_name': 'SM',
        'category': 'Imperium',
        'color': '#1a6bb5',
        'detachments': [
            {
                'name': 'Gladius Task Force',
                'ability_name': 'Finest Hour',
                'ability_text': 'Once per battle, at the start of your Command phase, one Infantry, Mounted, or Psyker unit from your army can use this ability. Until the start of your next Command phase, that unit is eligible to shoot and declare a charge in a turn in which it Fell Back.',
            },
            {
                'name': 'Vanguard Spearhead',
                'ability_name': 'Guerrilla Tactics',
                'ability_text': 'At the end of your opponent\'s turn, you can select one Phobos unit from your army. Remove that unit from the battlefield and place it into Strategic Reserves.',
            },
            {
                'name': 'Ironstorm Spearhead',
                'ability_name': 'Steel Rain',
                'ability_text': 'Each time a Vehicle or Mounted unit from your army makes a ranged attack, re-roll a Hit roll of 1.',
            },
        ],
        'units': [
            {
                'id': 'sm-captain',
                'name': 'Captain',
                'role': 'HQ',
                'base_points': 80,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '6"', 'T': 4, 'Sv': '3+', 'W': 5, 'Ld': '6+', 'OC': 1},
                'keywords': ['Infantry', 'Character', 'Grenades', 'Tacticus', 'Captain'],
                'faction_keywords': ['Adeptus Astartes'],
                'abilities': [
                    {'name': 'Rites of Battle', 'text': 'Friendly Adeptus Astartes Core units can use this model\'s Leadership when making Morale tests.'},
                    {'name': 'Inspiring Presence', 'text': 'Once per turn, when a friendly Adeptus Astartes Core unit within 6" of this model fails a Morale test, you can re-roll that test.'},
                ],
                'weapons': [
                    {'name': 'Master-crafted power weapon', 'range': 'Melee', 'attacks': 5, 'skill': '2+', 'strength': 5, 'ap': -2, 'damage': 2},
                    {'name': 'Neo-volkite pistol', 'range': '15"', 'attacks': 2, 'skill': '2+', 'strength': 5, 'ap': 0, 'damage': 2, 'keywords': ['Pistol']},
                ],
                'wargear_options': ['This model\'s neo-volkite pistol can be replaced with one of: bolt pistol; plasma pistol.'],
            },
            {
                'id': 'sm-librarian',
                'name': 'Librarian',
                'role': 'HQ',
                'base_points': 75,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '6"', 'T': 4, 'Sv': '3+', 'W': 4, 'Ld': '6+', 'OC': 1},
                'keywords': ['Infantry', 'Character', 'Grenades', 'Psyker', 'Tacticus', 'Librarian'],
                'faction_keywords': ['Adeptus Astartes'],
                'abilities': [
                    {'name': 'Psychic Hood', 'text': 'Each time an enemy Psyker model within 12" of this model attempts to manifest a psychic power, subtract 1 from that Psychic test.'},
                ],
                'weapons': [
                    {'name': 'Force weapon', 'range': 'Melee', 'attacks': 4, 'skill': '3+', 'strength': 6, 'ap': -1, 'damage': 2, 'keywords': ['Psychic']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'sm-tactical-squad',
                'name': 'Tactical Squad',
                'role': 'Troops',
                'base_points': 90,
                'points_per_model': 18,
                'is_character': False,
                'model_count_min': 5,
                'model_count_max': 10,
                'stats': {'M': '6"', 'T': 4, 'Sv': '3+', 'W': 2, 'Ld': '6+', 'OC': 2},
                'keywords': ['Infantry', 'Grenades', 'Tacticus', 'Tactical Squad'],
                'faction_keywords': ['Adeptus Astartes'],
                'abilities': [],
                'weapons': [
                    {'name': 'Bolt rifle', 'range': '24"', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1, 'keywords': ['Assault', 'Heavy']},
                    {'name': 'Bolt pistol', 'range': '12"', 'attacks': 1, 'skill': '3+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Pistol']},
                    {'name': 'Close combat weapon', 'range': 'Melee', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': 0, 'damage': 1},
                ],
                'wargear_options': ['The Sergeant\'s bolt rifle can be replaced with a power sword, power fist, or thunder hammer.'],
            },
            {
                'id': 'sm-intercessors',
                'name': 'Intercessor Squad',
                'role': 'Troops',
                'base_points': 85,
                'points_per_model': 17,
                'is_character': False,
                'model_count_min': 5,
                'model_count_max': 10,
                'stats': {'M': '6"', 'T': 4, 'Sv': '3+', 'W': 2, 'Ld': '6+', 'OC': 2},
                'keywords': ['Infantry', 'Grenades', 'Tacticus', 'Intercessor Squad'],
                'faction_keywords': ['Adeptus Astartes'],
                'abilities': [],
                'weapons': [
                    {'name': 'Bolt rifle', 'range': '24"', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1, 'keywords': ['Assault', 'Heavy']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'sm-assault-intercessors',
                'name': 'Assault Intercessor Squad',
                'role': 'Troops',
                'base_points': 75,
                'points_per_model': 15,
                'is_character': False,
                'model_count_min': 5,
                'model_count_max': 10,
                'stats': {'M': '6"', 'T': 4, 'Sv': '3+', 'W': 2, 'Ld': '6+', 'OC': 2},
                'keywords': ['Infantry', 'Grenades', 'Tacticus', 'Assault Intercessor Squad'],
                'faction_keywords': ['Adeptus Astartes'],
                'abilities': [],
                'weapons': [
                    {'name': 'Heavy bolt pistol', 'range': '12"', 'attacks': 1, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1, 'keywords': ['Pistol']},
                    {'name': 'Astartes chainsword', 'range': 'Melee', 'attacks': 4, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1},
                ],
                'wargear_options': [],
            },
            {
                'id': 'sm-dreadnought',
                'name': 'Dreadnought',
                'role': 'Elites',
                'base_points': 140,
                'points_per_model': 0,
                'is_character': False,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '6"', 'T': 9, 'Sv': '2+', 'W': 8, 'Ld': '6+', 'OC': 3},
                'keywords': ['Vehicle', 'Walker', 'Smoke', 'Dreadnought'],
                'faction_keywords': ['Adeptus Astartes'],
                'abilities': [],
                'weapons': [
                    {'name': 'Multi-melta', 'range': '18"', 'attacks': 2, 'skill': '3+', 'strength': 9, 'ap': -4, 'damage': 'D6+2', 'keywords': ['Melta 2']},
                    {'name': 'Dreadnought combat weapon', 'range': 'Melee', 'attacks': 5, 'skill': '3+', 'strength': 12, 'ap': -2, 'damage': 3},
                ],
                'wargear_options': [],
            },
            {
                'id': 'sm-aggressors',
                'name': 'Aggressor Squad',
                'role': 'Elites',
                'base_points': 120,
                'points_per_model': 40,
                'is_character': False,
                'model_count_min': 3,
                'model_count_max': 6,
                'stats': {'M': '5"', 'T': 5, 'Sv': '3+', 'W': 3, 'Ld': '6+', 'OC': 1},
                'keywords': ['Infantry', 'Gravis', 'Aggressor Squad'],
                'faction_keywords': ['Adeptus Astartes'],
                'abilities': [
                    {'name': 'Flamestorm Gauntlets', 'text': 'Each time this unit ends a Normal Move, it can shoot as if it were your Shooting phase.'},
                ],
                'weapons': [
                    {'name': 'Flamestorm gauntlets', 'range': '12"', 'attacks': 'D6', 'skill': 'N/A', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Torrent', 'Twin-linked']},
                    {'name': 'Power fists', 'range': 'Melee', 'attacks': 3, 'skill': '4+', 'strength': 8, 'ap': -2, 'damage': 2},
                ],
                'wargear_options': [],
            },
            {
                'id': 'sm-land-raider',
                'name': 'Land Raider',
                'role': 'Heavy Support',
                'base_points': 240,
                'points_per_model': 0,
                'is_character': False,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '10"', 'T': 12, 'Sv': '2+', 'W': 16, 'Ld': '6+', 'OC': 5},
                'keywords': ['Vehicle', 'Smoke', 'Transport', 'Dedicated Transport', 'Land Raider'],
                'faction_keywords': ['Adeptus Astartes'],
                'abilities': [{'name': 'Assault Ramp', 'text': 'Units can disembark from this Transport after it has made a Normal Move, but must Remain Stationary for the rest of the turn.'}],
                'weapons': [
                    {'name': 'Twin lascannon', 'range': '48"', 'attacks': 2, 'skill': '3+', 'strength': 12, 'ap': -3, 'damage': 'D6+1', 'keywords': ['Twin-linked']},
                    {'name': 'Twin heavy bolter', 'range': '36"', 'attacks': 6, 'skill': '3+', 'strength': 5, 'ap': -1, 'damage': 2, 'keywords': ['Sustained Hits 1', 'Twin-linked']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'sm-devastator-squad',
                'name': 'Devastator Squad',
                'role': 'Heavy Support',
                'base_points': 85,
                'points_per_model': 17,
                'is_character': False,
                'model_count_min': 5,
                'model_count_max': 10,
                'stats': {'M': '6"', 'T': 4, 'Sv': '3+', 'W': 2, 'Ld': '6+', 'OC': 2},
                'keywords': ['Infantry', 'Grenades', 'Tacticus', 'Devastator Squad'],
                'faction_keywords': ['Adeptus Astartes'],
                'abilities': [],
                'weapons': [
                    {'name': 'Missile launcher', 'range': '48"', 'attacks': 1, 'skill': '4+', 'strength': 10, 'ap': -2, 'damage': 'D6'},
                ],
                'wargear_options': ['Up to 4 models can each have their bolt pistol and bolt rifle replaced with one of: heavy bolter; lascannon; missile launcher; multi-melta; plasma cannon.'],
            },
            {
                'id': 'sm-bike-squad',
                'name': 'Outrider Squad',
                'role': 'Fast Attack',
                'base_points': 120,
                'points_per_model': 40,
                'is_character': False,
                'model_count_min': 3,
                'model_count_max': 6,
                'stats': {'M': '14"', 'T': 5, 'Sv': '3+', 'W': 4, 'Ld': '6+', 'OC': 2},
                'keywords': ['Mounted', 'Grenades', 'Tacticus', 'Outrider Squad'],
                'faction_keywords': ['Adeptus Astartes'],
                'abilities': [],
                'weapons': [
                    {'name': 'Astartes chainsword', 'range': 'Melee', 'attacks': 4, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1},
                    {'name': 'Twin bolt rifle', 'range': '24"', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1, 'keywords': ['Twin-linked', 'Assault', 'Heavy']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'sm-drop-pod',
                'name': 'Drop Pod',
                'role': 'Dedicated Transport',
                'base_points': 70,
                'points_per_model': 0,
                'is_character': False,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '0"', 'T': 9, 'Sv': '3+', 'W': 8, 'Ld': '6+', 'OC': 0},
                'keywords': ['Vehicle', 'Transport', 'Drop Pod'],
                'faction_keywords': ['Adeptus Astartes'],
                'abilities': [{'name': 'Drop Pod Assault', 'text': 'During deployment, you can set this model up in high orbit instead of on the battlefield. At the start of the first battle round, this model must make a Drop Pod Assault move.'}],
                'weapons': [
                    {'name': 'Storm bolter', 'range': '24"', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Rapid Fire 2']},
                ],
                'wargear_options': [],
            },
        ],
    },
    {
        'id': 'chaos-space-marines',
        'name': 'Chaos Space Marines',
        'short_name': 'CSM',
        'category': 'Chaos',
        'color': '#8b0000',
        'detachments': [
            {
                'name': 'Slaves to Darkness',
                'ability_name': 'Mark of Chaos',
                'ability_text': 'At the start of the battle, select a Mark of Chaos for your army: Mark of Khorne, Mark of Tzeentch, Mark of Nurgle, or Mark of Slaanesh. All Core units in your army gain the associated keyword.',
            },
            {
                'name': 'Heretic Astartes',
                'ability_name': 'Malicious Volleys',
                'ability_text': 'Each time a unit with this ability is selected to shoot, it can make additional attacks with bolt weapons.',
            },
        ],
        'units': [
            {
                'id': 'csm-chaos-lord',
                'name': 'Chaos Lord',
                'role': 'HQ',
                'base_points': 75,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '6"', 'T': 4, 'Sv': '3+', 'W': 5, 'Ld': '6+', 'OC': 1},
                'keywords': ['Infantry', 'Character', 'Chaos', 'Chaos Lord'],
                'faction_keywords': ['Heretic Astartes'],
                'abilities': [{'name': 'Aura of Dark Glory', 'text': 'Friendly Heretic Astartes Core units within 6" of this model can re-roll hit rolls of 1.'}],
                'weapons': [
                    {'name': 'Accursed weapon', 'range': 'Melee', 'attacks': 5, 'skill': '2+', 'strength': 5, 'ap': -2, 'damage': 2},
                    {'name': 'Bolt pistol', 'range': '12"', 'attacks': 1, 'skill': '2+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Pistol']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'csm-dark-apostle',
                'name': 'Dark Apostle',
                'role': 'HQ',
                'base_points': 65,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '6"', 'T': 4, 'Sv': '3+', 'W': 4, 'Ld': '6+', 'OC': 1},
                'keywords': ['Infantry', 'Character', 'Chaos', 'Dark Apostle'],
                'faction_keywords': ['Heretic Astartes'],
                'abilities': [{'name': 'Prayers to the Dark Gods', 'text': 'This model knows two prayers. It can attempt to pray once per turn.'}],
                'weapons': [
                    {'name': 'Cursed crozius', 'range': 'Melee', 'attacks': 4, 'skill': '2+', 'strength': 6, 'ap': -1, 'damage': 2},
                ],
                'wargear_options': [],
            },
            {
                'id': 'csm-chaos-marines',
                'name': 'Chaos Space Marines',
                'role': 'Troops',
                'base_points': 90,
                'points_per_model': 18,
                'is_character': False,
                'model_count_min': 5,
                'model_count_max': 10,
                'stats': {'M': '6"', 'T': 4, 'Sv': '3+', 'W': 2, 'Ld': '6+', 'OC': 2},
                'keywords': ['Infantry', 'Grenades', 'Chaos', 'Chaos Space Marines'],
                'faction_keywords': ['Heretic Astartes'],
                'abilities': [],
                'weapons': [
                    {'name': 'Bolt pistol', 'range': '12"', 'attacks': 1, 'skill': '3+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Pistol']},
                    {'name': 'Boltgun', 'range': '24"', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Rapid Fire 1']},
                    {'name': 'Astartes chainsword', 'range': 'Melee', 'attacks': 4, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1},
                ],
                'wargear_options': [],
            },
            {
                'id': 'csm-chosen',
                'name': 'Chosen',
                'role': 'Elites',
                'base_points': 90,
                'points_per_model': 18,
                'is_character': False,
                'model_count_min': 5,
                'model_count_max': 10,
                'stats': {'M': '6"', 'T': 4, 'Sv': '3+', 'W': 2, 'Ld': '6+', 'OC': 2},
                'keywords': ['Infantry', 'Grenades', 'Chaos', 'Chosen'],
                'faction_keywords': ['Heretic Astartes'],
                'abilities': [{'name': 'Veteran Fighters', 'text': 'Each time a model in this unit makes a melee attack, re-roll a Hit roll of 1.'}],
                'weapons': [
                    {'name': 'Accursed weapon', 'range': 'Melee', 'attacks': 4, 'skill': '3+', 'strength': 5, 'ap': -2, 'damage': 2},
                    {'name': 'Bolt pistol', 'range': '12"', 'attacks': 1, 'skill': '3+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Pistol']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'csm-obliterators',
                'name': 'Obliterators',
                'role': 'Elites',
                'base_points': 150,
                'points_per_model': 75,
                'is_character': False,
                'model_count_min': 2,
                'model_count_max': 4,
                'stats': {'M': '5"', 'T': 6, 'Sv': '2+', 'W': 4, 'Ld': '6+', 'OC': 1},
                'keywords': ['Infantry', 'Chaos', 'Obliterators'],
                'faction_keywords': ['Heretic Astartes'],
                'abilities': [{'name': 'Fleshmetal Guns', 'text': 'Each time this unit is selected to shoot, you can change the profile of the Obliterators\' fleshmetal guns to one of several options.'}],
                'weapons': [
                    {'name': 'Fleshmetal guns', 'range': '24"', 'attacks': 4, 'skill': '3+', 'strength': 8, 'ap': -2, 'damage': 3},
                    {'name': 'Massive chainfists', 'range': 'Melee', 'attacks': 3, 'skill': '4+', 'strength': 12, 'ap': -3, 'damage': 3},
                ],
                'wargear_options': [],
            },
            {
                'id': 'csm-havocs',
                'name': 'Havocs',
                'role': 'Heavy Support',
                'base_points': 85,
                'points_per_model': 17,
                'is_character': False,
                'model_count_min': 5,
                'model_count_max': 10,
                'stats': {'M': '6"', 'T': 4, 'Sv': '3+', 'W': 2, 'Ld': '6+', 'OC': 2},
                'keywords': ['Infantry', 'Grenades', 'Chaos', 'Havocs'],
                'faction_keywords': ['Heretic Astartes'],
                'abilities': [],
                'weapons': [
                    {'name': 'Lascannon', 'range': '48"', 'attacks': 1, 'skill': '4+', 'strength': 12, 'ap': -3, 'damage': 'D6+1'},
                    {'name': 'Heavy bolter', 'range': '36"', 'attacks': 3, 'skill': '4+', 'strength': 5, 'ap': -1, 'damage': 2},
                ],
                'wargear_options': ['Up to 4 Havocs can each have their boltgun replaced with one of: autocannon; heavy bolter; lascannon; missile launcher; reaper chaincannon.'],
            },
            {
                'id': 'csm-bikers',
                'name': 'Chaos Bikers',
                'role': 'Fast Attack',
                'base_points': 120,
                'points_per_model': 30,
                'is_character': False,
                'model_count_min': 3,
                'model_count_max': 6,
                'stats': {'M': '14"', 'T': 5, 'Sv': '3+', 'W': 3, 'Ld': '6+', 'OC': 2},
                'keywords': ['Mounted', 'Grenades', 'Chaos', 'Chaos Bikers'],
                'faction_keywords': ['Heretic Astartes'],
                'abilities': [],
                'weapons': [
                    {'name': 'Combi-bolter', 'range': '24"', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Rapid Fire 2']},
                    {'name': 'Astartes chainsword', 'range': 'Melee', 'attacks': 4, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1},
                ],
                'wargear_options': [],
            },
            {
                'id': 'csm-daemon-prince',
                'name': 'Daemon Prince',
                'role': 'HQ',
                'base_points': 155,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '8"', 'T': 7, 'Sv': '3+', 'W': 9, 'Ld': '6+', 'OC': 2},
                'keywords': ['Monster', 'Character', 'Chaos', 'Daemon', 'Daemon Prince'],
                'faction_keywords': ['Heretic Astartes'],
                'abilities': [{'name': 'Daemonic Terror', 'text': 'Each time an enemy unit fails a Battleshock test within 6" of this model, add D3 to the number of models that flee.'}],
                'weapons': [
                    {'name': 'Daemonic axe', 'range': 'Melee', 'attacks': 6, 'skill': '3+', 'strength': 10, 'ap': -3, 'damage': 3},
                    {'name': 'Hellforged talons', 'range': 'Melee', 'attacks': 6, 'skill': '3+', 'strength': 8, 'ap': -2, 'damage': 2},
                ],
                'wargear_options': [],
            },
        ],
    },
    {
        'id': 'necrons',
        'name': 'Necrons',
        'short_name': 'NEC',
        'category': 'Xenos',
        'color': '#00ff88',
        'detachments': [
            {
                'name': 'Awakened Dynasty',
                'ability_name': 'Relentless Expansionism',
                'ability_text': 'At the end of each player\'s turn, each Necrons unit from your army that is within range of an objective marker controls that objective marker, even if there are more enemy models within range.',
            },
            {
                'name': 'Canoptek Court',
                'ability_name': 'Adaptive Subroutines',
                'ability_text': 'Once per turn, one Canoptek unit from your army can be selected to activate twice in a single phase.',
            },
        ],
        'units': [
            {
                'id': 'nec-overlord',
                'name': 'Overlord',
                'role': 'HQ',
                'base_points': 85,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '5"', 'T': 5, 'Sv': '3+', 'W': 5, 'Ld': '6+', 'OC': 2},
                'keywords': ['Infantry', 'Character', 'Necrons', 'Noble', 'Overlord'],
                'faction_keywords': ['Necrons'],
                'abilities': [{'name': 'The Triarch\'s Will', 'text': 'Once per turn, you can select one friendly Necrons Core unit within 6" of this model. Until the end of the phase, each time a model in that unit makes an attack, re-roll a Hit roll of 1.'}],
                'weapons': [
                    {'name': 'Staff of light', 'range': '18"', 'attacks': 3, 'skill': '2+', 'strength': 5, 'ap': -2, 'damage': 1},
                    {'name': 'Staff of light', 'range': 'Melee', 'attacks': 3, 'skill': '2+', 'strength': 5, 'ap': -2, 'damage': 1},
                ],
                'wargear_options': [],
            },
            {
                'id': 'nec-cryptek',
                'name': 'Cryptek',
                'role': 'HQ',
                'base_points': 60,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '5"', 'T': 4, 'Sv': '4+', 'W': 4, 'Ld': '6+', 'OC': 1},
                'keywords': ['Infantry', 'Character', 'Necrons', 'Cryptek'],
                'faction_keywords': ['Necrons'],
                'abilities': [{'name': 'Rites of Reanimation', 'text': 'At the start of your Command phase, select one friendly Necrons Infantry or Mounted unit within 6" of this model. D3 destroyed models from that unit are returned to its starting strength.'}],
                'weapons': [
                    {'name': 'Eldritch lance', 'range': '36"', 'attacks': 1, 'skill': '2+', 'strength': 8, 'ap': -2, 'damage': 2},
                    {'name': 'Staff of light', 'range': 'Melee', 'attacks': 2, 'skill': '3+', 'strength': 5, 'ap': -2, 'damage': 1},
                ],
                'wargear_options': [],
            },
            {
                'id': 'nec-warriors',
                'name': 'Necron Warriors',
                'role': 'Troops',
                'base_points': 100,
                'points_per_model': 10,
                'is_character': False,
                'model_count_min': 10,
                'model_count_max': 20,
                'stats': {'M': '5"', 'T': 4, 'Sv': '4+', 'W': 1, 'Ld': '7+', 'OC': 2},
                'keywords': ['Infantry', 'Necrons', 'Reanimation Protocols', 'Warrior'],
                'faction_keywords': ['Necrons'],
                'abilities': [{'name': 'Reanimation Protocols', 'text': 'At the end of the phase in which one or more models from this unit were destroyed, roll one D6 for each destroyed model. For each roll of 5+, one destroyed model is returned with 1 wound.'}],
                'weapons': [
                    {'name': 'Gauss flayer', 'range': '24"', 'attacks': 1, 'skill': '4+', 'strength': 4, 'ap': -1, 'damage': 1, 'keywords': ['Rapid Fire 1']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'nec-immortals',
                'name': 'Immortals',
                'role': 'Troops',
                'base_points': 85,
                'points_per_model': 17,
                'is_character': False,
                'model_count_min': 5,
                'model_count_max': 10,
                'stats': {'M': '5"', 'T': 5, 'Sv': '3+', 'W': 2, 'Ld': '7+', 'OC': 2},
                'keywords': ['Infantry', 'Necrons', 'Reanimation Protocols', 'Immortal'],
                'faction_keywords': ['Necrons'],
                'abilities': [{'name': 'Reanimation Protocols', 'text': 'Same as Warriors.'}],
                'weapons': [
                    {'name': 'Gauss blaster', 'range': '24"', 'attacks': 2, 'skill': '3+', 'strength': 5, 'ap': -2, 'damage': 1, 'keywords': ['Rapid Fire 1']},
                ],
                'wargear_options': ['This unit\'s gauss blasters can be replaced with tesla carbines.'],
            },
            {
                'id': 'nec-lychguard',
                'name': 'Lychguard',
                'role': 'Elites',
                'base_points': 95,
                'points_per_model': 19,
                'is_character': False,
                'model_count_min': 5,
                'model_count_max': 10,
                'stats': {'M': '5"', 'T': 5, 'Sv': '3+', 'W': 3, 'Ld': '6+', 'OC': 2},
                'keywords': ['Infantry', 'Necrons', 'Lychguard'],
                'faction_keywords': ['Necrons'],
                'abilities': [],
                'weapons': [
                    {'name': 'Hyperphase sword', 'range': 'Melee', 'attacks': 3, 'skill': '3+', 'strength': 6, 'ap': -3, 'damage': 2},
                ],
                'wargear_options': ['Each model can have its hyperphase sword and dispersion shield replaced with a warscythe.'],
            },
            {
                'id': 'nec-canoptek-spyder',
                'name': 'Canoptek Spyder',
                'role': 'Elites',
                'base_points': 80,
                'points_per_model': 0,
                'is_character': False,
                'model_count_min': 1,
                'model_count_max': 3,
                'stats': {'M': '8"', 'T': 7, 'Sv': '3+', 'W': 5, 'Ld': '6+', 'OC': 2},
                'keywords': ['Canoptek', 'Monster', 'Fly', 'Canoptek Spyder'],
                'faction_keywords': ['Necrons'],
                'abilities': [{'name': 'Fabricator Claw Array', 'text': 'At the start of your Command phase, roll one D6 for each Canoptek Scarab Swarm model within 6" of this model. For each 5+, add 1 swarm base to that unit.'}],
                'weapons': [
                    {'name': 'Automaton claws', 'range': 'Melee', 'attacks': 4, 'skill': '3+', 'strength': 8, 'ap': -1, 'damage': 2},
                ],
                'wargear_options': [],
            },
            {
                'id': 'nec-annihilation-barge',
                'name': 'Annihilation Barge',
                'role': 'Heavy Support',
                'base_points': 115,
                'points_per_model': 0,
                'is_character': False,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '12"', 'T': 9, 'Sv': '3+', 'W': 8, 'Ld': '6+', 'OC': 3},
                'keywords': ['Vehicle', 'Fly', 'Necrons', 'Annihilation Barge'],
                'faction_keywords': ['Necrons'],
                'abilities': [],
                'weapons': [
                    {'name': 'Tesla destructor', 'range': '24"', 'attacks': 4, 'skill': '3+', 'strength': 7, 'ap': -1, 'damage': 2, 'keywords': ['Tesla']},
                    {'name': 'Twin gauss flayer', 'range': '24"', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1, 'keywords': ['Rapid Fire 1', 'Twin-linked']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'nec-doomsday-ark',
                'name': 'Doomsday Ark',
                'role': 'Heavy Support',
                'base_points': 195,
                'points_per_model': 0,
                'is_character': False,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '10"', 'T': 10, 'Sv': '3+', 'W': 14, 'Ld': '6+', 'OC': 4},
                'keywords': ['Vehicle', 'Fly', 'Necrons', 'Doomsday Ark'],
                'faction_keywords': ['Necrons'],
                'abilities': [],
                'weapons': [
                    {'name': 'Doomsday cannon (low power)', 'range': '48"', 'attacks': 'D6', 'skill': '3+', 'strength': 10, 'ap': -3, 'damage': 'D6'},
                    {'name': 'Doomsday cannon (high power)', 'range': '48"', 'attacks': 'D6', 'skill': '3+', 'strength': 20, 'ap': -5, 'damage': 'D6+6'},
                ],
                'wargear_options': [],
            },
            {
                'id': 'nec-wraiths',
                'name': 'Canoptek Wraiths',
                'role': 'Fast Attack',
                'base_points': 105,
                'points_per_model': 35,
                'is_character': False,
                'model_count_min': 3,
                'model_count_max': 6,
                'stats': {'M': '10"', 'T': 5, 'Sv': '3+', 'W': 3, 'Ld': '6+', 'OC': 1},
                'keywords': ['Canoptek', 'Fly', 'Canoptek Wraith'],
                'faction_keywords': ['Necrons'],
                'abilities': [{'name': 'Wraith Form', 'text': 'Models in this unit have a 4+ invulnerable save.'}],
                'weapons': [
                    {'name': 'Vicious claws', 'range': 'Melee', 'attacks': 4, 'skill': '3+', 'strength': 6, 'ap': -2, 'damage': 2},
                ],
                'wargear_options': [],
            },
        ],
    },
    {
        'id': 'tyranids',
        'name': 'Tyranids',
        'short_name': 'TYR',
        'category': 'Xenos',
        'color': '#9b30ff',
        'detachments': [
            {
                'name': 'Invasion Fleet',
                'ability_name': 'Synaptic Imperatives',
                'ability_text': 'At the start of your Command phase, choose one of the following Synaptic Imperatives for your army: Adrenal Surge, Synaptic Barrier, or Bio-instincts.',
            },
            {
                'name': 'Crusher Stampede',
                'ability_name': 'Unstoppable Momentum',
                'ability_text': 'Each time a Monster unit from your army ends a Charge move, roll one D6 for each enemy unit within Engagement Range of it: on a 4+, that enemy unit suffers D3 mortal wounds.',
            },
        ],
        'units': [
            {
                'id': 'tyr-hive-tyrant',
                'name': 'Hive Tyrant',
                'role': 'HQ',
                'base_points': 220,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '8"', 'T': 10, 'Sv': '2+', 'W': 12, 'Ld': '7+', 'OC': 3},
                'keywords': ['Monster', 'Character', 'Fly', 'Psyker', 'Synapse', 'Tyranid', 'Hive Tyrant'],
                'faction_keywords': ['Tyranids'],
                'abilities': [
                    {'name': 'Shadow in the Warp', 'text': 'While a friendly Psyker unit is within Synapse range of this model, that unit has Strength Perils. While an enemy Psyker unit is within 12" of this model, that unit must subtract 1 from all Psychic tests.'},
                    {'name': 'Hive Commander', 'text': 'Once per battle, in your Command phase, you can pick one friendly Tyranids unit within 6" of this model. That unit can immediately make a Normal Move.'},
                ],
                'weapons': [
                    {'name': 'Monstrous rending claws', 'range': 'Melee', 'attacks': 5, 'skill': '2+', 'strength': 10, 'ap': -3, 'damage': 3},
                    {'name': 'Stranglethorn cannon', 'range': '36"', 'attacks': 'D6', 'skill': '3+', 'strength': 8, 'ap': -2, 'damage': 2},
                ],
                'wargear_options': [],
            },
            {
                'id': 'tyr-broodlord',
                'name': 'Broodlord',
                'role': 'HQ',
                'base_points': 130,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '8"', 'T': 6, 'Sv': '4+', 'W': 8, 'Ld': '7+', 'OC': 2},
                'keywords': ['Infantry', 'Character', 'Psyker', 'Genestealers', 'Synapse', 'Tyranid', 'Broodlord'],
                'faction_keywords': ['Tyranids'],
                'abilities': [{'name': 'Lord of Genestealers', 'text': 'Genestealer units within 6" of this model can re-roll hit rolls of 1 in the Fight phase.'}],
                'weapons': [
                    {'name': 'Monstrous rending claws', 'range': 'Melee', 'attacks': 6, 'skill': '2+', 'strength': 8, 'ap': -3, 'damage': 2},
                ],
                'wargear_options': [],
            },
            {
                'id': 'tyr-termagants',
                'name': 'Termagants',
                'role': 'Troops',
                'base_points': 60,
                'points_per_model': 6,
                'is_character': False,
                'model_count_min': 10,
                'model_count_max': 20,
                'stats': {'M': '6"', 'T': 3, 'Sv': '5+', 'W': 1, 'Ld': '8+', 'OC': 2},
                'keywords': ['Infantry', 'Tyranid', 'Termagant'],
                'faction_keywords': ['Tyranids'],
                'abilities': [],
                'weapons': [
                    {'name': 'Fleshborer', 'range': '18"', 'attacks': 1, 'skill': '4+', 'strength': 5, 'ap': 0, 'damage': 1, 'keywords': ['Assault']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'tyr-hormagaunts',
                'name': 'Hormagaunts',
                'role': 'Troops',
                'base_points': 60,
                'points_per_model': 6,
                'is_character': False,
                'model_count_min': 10,
                'model_count_max': 20,
                'stats': {'M': '8"', 'T': 3, 'Sv': '5+', 'W': 1, 'Ld': '8+', 'OC': 2},
                'keywords': ['Infantry', 'Tyranid', 'Hormagaunt'],
                'faction_keywords': ['Tyranids'],
                'abilities': [{'name': 'Bounding Leap', 'text': 'Each time this unit makes a Normal Move, Advance, or Fall Back, models in this unit can move horizontally through models and terrain features. Each time this unit makes a Charge move, add 1" to that move.'}],
                'weapons': [
                    {'name': 'Scything talons', 'range': 'Melee', 'attacks': 3, 'skill': '4+', 'strength': 3, 'ap': -1, 'damage': 1},
                ],
                'wargear_options': [],
            },
            {
                'id': 'tyr-genestealers',
                'name': 'Genestealers',
                'role': 'Elites',
                'base_points': 120,
                'points_per_model': 20,
                'is_character': False,
                'model_count_min': 6,
                'model_count_max': 12,
                'stats': {'M': '8"', 'T': 4, 'Sv': '5+', 'W': 2, 'Ld': '7+', 'OC': 2},
                'keywords': ['Infantry', 'Genestealers', 'Tyranid'],
                'faction_keywords': ['Tyranids'],
                'abilities': [{'name': 'Lightning Reflexes', 'text': 'Models in this unit have a 5+ invulnerable save.'}],
                'weapons': [
                    {'name': 'Rending claws', 'range': 'Melee', 'attacks': 4, 'skill': '3+', 'strength': 5, 'ap': -3, 'damage': 2},
                ],
                'wargear_options': [],
            },
            {
                'id': 'tyr-carnifex',
                'name': 'Carnifex',
                'role': 'Heavy Support',
                'base_points': 140,
                'points_per_model': 0,
                'is_character': False,
                'model_count_min': 1,
                'model_count_max': 2,
                'stats': {'M': '6"', 'T': 10, 'Sv': '2+', 'W': 10, 'Ld': '8+', 'OC': 3},
                'keywords': ['Monster', 'Tyranid', 'Carnifex'],
                'faction_keywords': ['Tyranids'],
                'abilities': [{'name': 'Living Battering Ram', 'text': 'Add 1 to charge rolls made for this unit. Each time this unit ends a Charge move, roll one D6 for each enemy unit within Engagement Range of it: on a 2+, that enemy unit suffers D3 mortal wounds.'}],
                'weapons': [
                    {'name': 'Monstrous scything talons', 'range': 'Melee', 'attacks': 4, 'skill': '3+', 'strength': 12, 'ap': -2, 'damage': 3},
                    {'name': 'Bio-plasma', 'range': '18"', 'attacks': 'D3', 'skill': '4+', 'strength': 8, 'ap': -2, 'damage': 2},
                ],
                'wargear_options': [],
            },
            {
                'id': 'tyr-raveners',
                'name': 'Raveners',
                'role': 'Fast Attack',
                'base_points': 90,
                'points_per_model': 30,
                'is_character': False,
                'model_count_min': 3,
                'model_count_max': 9,
                'stats': {'M': '10"', 'T': 5, 'Sv': '4+', 'W': 3, 'Ld': '8+', 'OC': 2},
                'keywords': ['Beast', 'Tyranid', 'Ravener'],
                'faction_keywords': ['Tyranids'],
                'abilities': [],
                'weapons': [
                    {'name': 'Rending claws', 'range': 'Melee', 'attacks': 3, 'skill': '3+', 'strength': 5, 'ap': -3, 'damage': 2},
                    {'name': 'Spinefists', 'range': '12"', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Pistol', 'Twin-linked']},
                ],
                'wargear_options': [],
            },
        ],
    },
    {
        'id': 'orks',
        'name': 'Orks',
        'short_name': 'ORK',
        'category': 'Xenos',
        'color': '#4a7a1e',
        'detachments': [
            {
                'name': 'Waaagh! Tribe',
                'ability_name': 'Waaagh!',
                'ability_text': 'Once per battle, in your Command phase, you can declare a Waaagh!. Until the start of your next Command phase, all Ork units in your army add 1 to their Charge distance and gain the Fights First ability.',
            },
            {
                'name': 'Bully Boyz',
                'ability_name': 'Brutal But Kunnin\'',
                'ability_text': 'Each time a Nobz unit from your army fights, if it made a Charge move this turn, add 1 to the Attacks characteristic of models in that unit for that fight.',
            },
        ],
        'units': [
            {
                'id': 'ork-warboss',
                'name': 'Warboss',
                'role': 'HQ',
                'base_points': 80,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '5"', 'T': 5, 'Sv': '4+', 'W': 6, 'Ld': '7+', 'OC': 2},
                'keywords': ['Infantry', 'Character', 'Ork', 'Warboss'],
                'faction_keywords': ['Orks'],
                'abilities': [{'name': 'Waaagh! Leader', 'text': 'Once per battle, this model can call a Waaagh!, even if another model has already called one this battle.'}],
                'weapons': [
                    {'name': 'Power klaw', 'range': 'Melee', 'attacks': 4, 'skill': '2+', 'strength': 10, 'ap': -2, 'damage': 2},
                    {'name': 'Twin slugga', 'range': '12"', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Pistol', 'Twin-linked']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'ork-weirdboy',
                'name': 'Weirdboy',
                'role': 'HQ',
                'base_points': 55,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '5"', 'T': 4, 'Sv': '6+', 'W': 4, 'Ld': '7+', 'OC': 1},
                'keywords': ['Infantry', 'Character', 'Ork', 'Psyker', 'Weirdboy'],
                'faction_keywords': ['Orks'],
                'abilities': [{'name': 'Waaagh! Energy', 'text': 'If a Waaagh! has been declared, add 1 to all Psychic tests made for this model.'}],
                'weapons': [
                    {'name': 'Weirdboy staff', 'range': 'Melee', 'attacks': 3, 'skill': '3+', 'strength': 6, 'ap': -1, 'damage': 2},
                ],
                'wargear_options': [],
            },
            {
                'id': 'ork-boyz',
                'name': 'Boyz',
                'role': 'Troops',
                'base_points': 80,
                'points_per_model': 8,
                'is_character': False,
                'model_count_min': 10,
                'model_count_max': 20,
                'stats': {'M': '5"', 'T': 4, 'Sv': '6+', 'W': 1, 'Ld': '7+', 'OC': 2},
                'keywords': ['Infantry', 'Ork', 'Boy'],
                'faction_keywords': ['Orks'],
                'abilities': [{'name': 'Mob Rule', 'text': 'Orks never take Morale tests. Instead, at the start of each Morale phase, if this unit has fewer than half its starting number of models remaining, it must make a Mob Rule check.'}],
                'weapons': [
                    {'name': 'Choppa', 'range': 'Melee', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1},
                    {'name': 'Slugga', 'range': '12"', 'attacks': 1, 'skill': '5+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Pistol']},
                ],
                'wargear_options': ['The Nob\'s choppa and slugga can be replaced with a big choppa or power klaw.'],
            },
            {
                'id': 'ork-nobz',
                'name': 'Nobz',
                'role': 'Elites',
                'base_points': 70,
                'points_per_model': 14,
                'is_character': False,
                'model_count_min': 5,
                'model_count_max': 10,
                'stats': {'M': '5"', 'T': 5, 'Sv': '4+', 'W': 2, 'Ld': '7+', 'OC': 2},
                'keywords': ['Infantry', 'Ork', 'Nob'],
                'faction_keywords': ['Orks'],
                'abilities': [],
                'weapons': [
                    {'name': 'Big choppa', 'range': 'Melee', 'attacks': 3, 'skill': '3+', 'strength': 7, 'ap': -1, 'damage': 2},
                    {'name': 'Slugga', 'range': '12"', 'attacks': 1, 'skill': '5+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Pistol']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'ork-stormboyz',
                'name': 'Stormboyz',
                'role': 'Fast Attack',
                'base_points': 70,
                'points_per_model': 7,
                'is_character': False,
                'model_count_min': 10,
                'model_count_max': 20,
                'stats': {'M': '5"', 'T': 4, 'Sv': '6+', 'W': 1, 'Ld': '7+', 'OC': 2},
                'keywords': ['Infantry', 'Jump Pack', 'Fly', 'Ork', 'Stormboy'],
                'faction_keywords': ['Orks'],
                'abilities': [{'name': 'Rokkit Pack', 'text': 'In your Movement phase, when this unit Advances, add 6" to the Move characteristic of models in this unit for that move.'}],
                'weapons': [
                    {'name': 'Choppa', 'range': 'Melee', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1},
                    {'name': 'Slugga', 'range': '12"', 'attacks': 1, 'skill': '5+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Pistol']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'ork-deff-dread',
                'name': 'Deff Dread',
                'role': 'Heavy Support',
                'base_points': 110,
                'points_per_model': 0,
                'is_character': False,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '6"', 'T': 9, 'Sv': '3+', 'W': 8, 'Ld': '7+', 'OC': 3},
                'keywords': ['Vehicle', 'Walker', 'Ork', 'Deff Dread'],
                'faction_keywords': ['Orks'],
                'abilities': [],
                'weapons': [
                    {'name': 'Klaw of Gork (Mega-force klaw)', 'range': 'Melee', 'attacks': 5, 'skill': '3+', 'strength': 12, 'ap': -3, 'damage': 3},
                ],
                'wargear_options': ['Can replace weapons with: big shoota, kustom mega-blasta, rokkit launcha, or skorcha.'],
            },
            {
                'id': 'ork-warbikers',
                'name': 'Warbikers',
                'role': 'Fast Attack',
                'base_points': 75,
                'points_per_model': 25,
                'is_character': False,
                'model_count_min': 3,
                'model_count_max': 9,
                'stats': {'M': '14"', 'T': 5, 'Sv': '4+', 'W': 3, 'Ld': '7+', 'OC': 2},
                'keywords': ['Mounted', 'Ork', 'Warbiker'],
                'faction_keywords': ['Orks'],
                'abilities': [],
                'weapons': [
                    {'name': 'Twin dakkagun', 'range': '18"', 'attacks': 4, 'skill': '5+', 'strength': 5, 'ap': 0, 'damage': 1, 'keywords': ['Twin-linked']},
                    {'name': 'Choppa', 'range': 'Melee', 'attacks': 2, 'skill': '3+', 'strength': 4, 'ap': -1, 'damage': 1},
                ],
                'wargear_options': [],
            },
        ],
    },
    {
        'id': 'tau-empire',
        'name': "T'au Empire",
        'short_name': "T'AU",
        'category': 'Xenos',
        'color': '#4bbcff',
        'detachments': [
            {
                'name': 'Kauyon',
                'ability_name': 'Patient Hunter',
                'ability_text': 'Once per turn, when a T\'au Empire unit from your army that has not moved this turn is selected to shoot, all ranged weapons that model or unit is equipped with gain the Precision ability until the end of the phase.',
            },
            {
                'name': 'Mont\'ka',
                'ability_name': 'Killing Blow',
                'ability_text': 'Each time a T\'au Empire unit from your army is selected to shoot, if it has not moved this turn, models in that unit do not suffer the penalty to hit rolls for moving and shooting Heavy weapons.',
            },
        ],
        'units': [
            {
                'id': 'tau-commander',
                'name': 'Commander in Coldstar Battlesuit',
                'role': 'HQ',
                'base_points': 130,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '14"', 'T': 5, 'Sv': '2+', 'W': 6, 'Ld': '6+', 'OC': 2},
                'keywords': ['Monster', 'Character', 'Fly', 'Battlesuit', 'Commander'],
                'faction_keywords': ["T'au Empire"],
                'abilities': [{'name': 'Master of War', 'text': 'Once per battle, this model can issue the Designated Target order for 0CP.'}],
                'weapons': [
                    {'name': 'High-output burst cannon', 'range': '18"', 'attacks': 8, 'skill': '4+', 'strength': 6, 'ap': 0, 'damage': 1},
                    {'name': 'Airbursting fragmentation projector', 'range': '18"', 'attacks': 'D6', 'skill': '4+', 'strength': 4, 'ap': 0, 'damage': 1, 'keywords': ['Indirect Fire', 'Blast']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'tau-ethereal',
                'name': 'Ethereal',
                'role': 'HQ',
                'base_points': 55,
                'points_per_model': 0,
                'is_character': True,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '6"', 'T': 3, 'Sv': '5+', 'W': 3, 'Ld': '6+', 'OC': 1},
                'keywords': ['Infantry', 'Character', "T'au", 'Ethereal'],
                'faction_keywords': ["T'au Empire"],
                'abilities': [{'name': 'Invocations of the Ethereals', 'text': 'This model knows one of the following invocations. In your Command phase, this model can use it: Sense of Stone, Zephyr\'s Grace, or Storm of Fire.'}],
                'weapons': [
                    {'name': 'Honour stave', 'range': 'Melee', 'attacks': 3, 'skill': '4+', 'strength': 4, 'ap': -1, 'damage': 2},
                ],
                'wargear_options': [],
            },
            {
                'id': 'tau-fire-warriors',
                'name': 'Fire Warriors Strike Team',
                'role': 'Troops',
                'base_points': 80,
                'points_per_model': 8,
                'is_character': False,
                'model_count_min': 10,
                'model_count_max': 20,
                'stats': {'M': '6"', 'T': 3, 'Sv': '4+', 'W': 1, 'Ld': '7+', 'OC': 2},
                'keywords': ['Infantry', "T'au", 'Fire Warrior', 'Strike Team'],
                'faction_keywords': ["T'au Empire"],
                'abilities': [],
                'weapons': [
                    {'name': 'Pulse rifle', 'range': '30"', 'attacks': 1, 'skill': '4+', 'strength': 5, 'ap': -2, 'damage': 1, 'keywords': ['Rapid Fire 1']},
                    {'name': 'Pulse pistol', 'range': '12"', 'attacks': 1, 'skill': '4+', 'strength': 5, 'ap': -2, 'damage': 1, 'keywords': ['Pistol']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'tau-pathfinders',
                'name': 'Pathfinder Team',
                'role': 'Fast Attack',
                'base_points': 55,
                'points_per_model': 11,
                'is_character': False,
                'model_count_min': 5,
                'model_count_max': 10,
                'stats': {'M': '7"', 'T': 3, 'Sv': '5+', 'W': 1, 'Ld': '7+', 'OC': 2},
                'keywords': ['Infantry', "T'au", 'Pathfinder'],
                'faction_keywords': ["T'au Empire"],
                'abilities': [{'name': 'Markerlight', 'text': 'Each time an attack is made with a Markerlight, if a hit is scored, the target unit gains a Markerlight token.'}],
                'weapons': [
                    {'name': 'Pulse carbine', 'range': '20"', 'attacks': 2, 'skill': '4+', 'strength': 5, 'ap': -2, 'damage': 1, 'keywords': ['Assault']},
                    {'name': 'Markerlight', 'range': '36"', 'attacks': 1, 'skill': '4+', 'strength': 1, 'ap': 0, 'damage': 0, 'keywords': ['Markerlight']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'tau-crisis-suits',
                'name': 'Crisis Battlesuits',
                'role': 'Elites',
                'base_points': 75,
                'points_per_model': 25,
                'is_character': False,
                'model_count_min': 3,
                'model_count_max': 9,
                'stats': {'M': '8"', 'T': 5, 'Sv': '3+', 'W': 3, 'Ld': '6+', 'OC': 1},
                'keywords': ['Monster', 'Fly', 'Battlesuit', 'Crisis'],
                'faction_keywords': ["T'au Empire"],
                'abilities': [],
                'weapons': [
                    {'name': 'Burst cannon', 'range': '18"', 'attacks': 4, 'skill': '4+', 'strength': 5, 'ap': 0, 'damage': 1},
                    {'name': 'Fusion blaster', 'range': '12"', 'attacks': 1, 'skill': '4+', 'strength': 9, 'ap': -4, 'damage': 'D6', 'keywords': ['Melta 2']},
                ],
                'wargear_options': ['Each model can be equipped with up to 3 items from the following: burst cannon, cyclic ion blaster, flamer, fusion blaster, missile pod, plasma rifle, or smart missile system.'],
            },
            {
                'id': 'tau-broadsides',
                'name': 'Broadside Battlesuits',
                'role': 'Heavy Support',
                'base_points': 90,
                'points_per_model': 90,
                'is_character': False,
                'model_count_min': 1,
                'model_count_max': 3,
                'stats': {'M': '5"', 'T': 6, 'Sv': '2+', 'W': 6, 'Ld': '6+', 'OC': 2},
                'keywords': ['Monster', 'Battlesuit', 'Broadside'],
                'faction_keywords': ["T'au Empire"],
                'abilities': [],
                'weapons': [
                    {'name': 'Heavy rail rifle', 'range': '60"', 'attacks': 2, 'skill': '4+', 'strength': 10, 'ap': -4, 'damage': 'D6+2'},
                    {'name': 'Twin smart missile system', 'range': '30"', 'attacks': 4, 'skill': '4+', 'strength': 5, 'ap': 0, 'damage': 1, 'keywords': ['Twin-linked', 'Indirect Fire']},
                ],
                'wargear_options': [],
            },
            {
                'id': 'tau-hammerhead',
                'name': 'Hammerhead Gunship',
                'role': 'Heavy Support',
                'base_points': 130,
                'points_per_model': 0,
                'is_character': False,
                'model_count_min': 1,
                'model_count_max': 1,
                'stats': {'M': '12"', 'T': 10, 'Sv': '3+', 'W': 13, 'Ld': '6+', 'OC': 3},
                'keywords': ['Vehicle', 'Fly', 'Hammerhead'],
                'faction_keywords': ["T'au Empire"],
                'abilities': [],
                'weapons': [
                    {'name': 'Railgun', 'range': '72"', 'attacks': 1, 'skill': '4+', 'strength': 20, 'ap': -8, 'damage': 'D6+6', 'keywords': ['Devastating Wounds']},
                    {'name': 'Twin burst cannon', 'range': '18"', 'attacks': 8, 'skill': '4+', 'strength': 6, 'ap': 0, 'damage': 1, 'keywords': ['Twin-linked']},
                ],
                'wargear_options': ['This model\'s railgun can be replaced with an ion cannon.'],
            },
        ],
    },
]


class Command(BaseCommand):
    help = 'Populate Army Builder with Warhammer 40k 10th edition data'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear existing builder data before populating',
        )

    def handle(self, *args, **options):
        if options['clear']:
            self.stdout.write('Clearing existing builder data...')
            BuilderDatasheet.objects.all().delete()
            BuilderFaction.objects.all().delete()

        created_factions = 0
        created_units = 0
        updated_factions = 0
        updated_units = 0

        for faction_data in FACTIONS_DATA:
            units_data = faction_data.pop('units')

            faction, created = BuilderFaction.objects.update_or_create(
                id=faction_data['id'],
                defaults=faction_data,
            )
            if created:
                created_factions += 1
            else:
                updated_factions += 1

            for unit_data in units_data:
                unit_id = unit_data.pop('id')
                unit_data['faction'] = faction

                datasheet, created = BuilderDatasheet.objects.update_or_create(
                    id=unit_id,
                    defaults=unit_data,
                )
                if created:
                    created_units += 1
                else:
                    updated_units += 1

            # Restore units_data for logging
            faction_data['units'] = units_data

        self.stdout.write(
            self.style.SUCCESS(
                f'Done! Factions: {created_factions} created, {updated_factions} updated. '
                f'Units: {created_units} created, {updated_units} updated.'
            )
        )
